### ISSUE TITLE
I2C address of ES8388

### ISSUE THREAD

**Issue by vanniaz** [thaaraak/ESP32-ES8388#1]
Hello, just a quick question: I see that in the original ES8388.h file ES8388_ADDR is defined as 0x20 while in your code you define it as 0b0010000 (i.e. 0x10), can you explain?
Thank you

**Comment by thaaraak** [comment]
If I recall its because the address gets shifted left one bit. The zeroth bit is reserved for read vs write indicator.

**Comment by vanniaz** [comment]
OK thank you. I overlooked the fact that you are using i2c_bus_addr << 1 in the i2c calls. Now it is clear.
